export const CUSTOMER_LEVEL_COMMISSIONS = {
  CITY_MANAGER: {
    commission: 10
  },
  STATE_MANAGER: {
    commission: 20
  },
  NATIONAL_MANAGER: {
    commission: 30
  },
  REGIONAL_MANAGER: {
    commission: 40
  }
}

export const USER_ROLES = {
  ADMIN: 'ADMIN',
  AFFILIATE: 'AFFILIATE',
  CUSTOMER: 'CUSTOMER',
  CUSTOMER_WHOLESALE: 'CUSTOMER_WHOLESALE',
  CITY_MANAGER: 'CITY_MANAGER',
  STATE_MANAGER: 'STATE_MANAGER',
  NATIONAL_MANAGER: 'NATIONAL_MANAGER',
  REGIONAL_MANAGER: 'REGIONAL_MANAGER'
}
